--create table EmployeeDemographics
--(EmployeeID int,
--FirstName varchar(50),
--LastName varchar(50),
--Age int,
--Gender varchar(50)
--)

--create table EmplyeeSalary
--(EmployeeId int,
--JobTitle varchar(50),
--Salary int
--)
